#!/bin/sh

if [ -z "$NODE_PATH" ];
then
  nodejs_mods="/opt/nodejs/node_modules"
  nodejs12_mods="/opt/nodejs/node12/node_modules"
  runtime_mods="/var/runtime/node_modules"
  export NODE_PATH="$nodejs12_mods:$nodejs_mods:$runtime_mods"
fi

if [ -n "$AWS_LAMBDA_FUNCTION_MEMORY_SIZE" ];
then
  new_space=$(expr $AWS_LAMBDA_FUNCTION_MEMORY_SIZE / 10)
  semi_space=$(expr $new_space / 2)
  old_space=$(expr $AWS_LAMBDA_FUNCTION_MEMORY_SIZE - $new_space)
  MEMORY_ARGS=(
    "--max-semi-space-size=$semi_space"
    "--max-old-space-size=$old_space"
  )
fi

exec env \
  /var/lang/bin/node \
  --expose-gc \
  --max-http-header-size 81920 \
  "${MEMORY_ARGS[@]}" \
  /var/runtime/index.js
